services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - path: ./envs/.env.production
        required: false
    ports:
      - "3424:3424"
    environment:
      - PORT=3424
      - NODE_ENV=production
    labels:
      app: nestjs
      env: test
      team: backend
      service: nest-template-lite-2025
    restart: unless-stopped
